In [1]:
import pandas as pd

In [2]:
#Read the file by giving the path address from file explorer.
file_path = r"C:\Users\jagru\Downloads\Datasets\movies-db-1_dataset.xlsx"

In [3]:
#Read different excel sheets from the main file and store it into a variables.
movies = pd.read_excel(file_path,sheet_name = "movies")
financials = pd.read_excel(file_path,sheet_name = "financials")
actors = pd.read_excel(file_path,sheet_name = "actors")
movie_actor = pd.read_excel(file_path,sheet_name = "movie_actor")
languages = pd.read_excel(file_path,sheet_name = "languages")

In [4]:
#Head will return First 5 rows of data from dataset.
movies.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [5]:
type(movies)

pandas.core.frame.DataFrame

In [6]:
#shape returns (coloumns,rows) number
movies.shape

(39, 7)

In [7]:
movies.columns

Index(['movie_id', 'title', 'industry', 'release_year', 'imdb_rating',
       'studio', 'language_id'],
      dtype='object')

In [8]:
movies.dtypes

movie_id          int64
title            object
industry         object
release_year      int64
imdb_rating     float64
studio           object
language_id       int64
dtype: object

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      39 non-null     int64
 1   title         39 non-null     object
 2   industry      39 non-null     object
 3   release_year  39 non-null     int64
 4   imdb_rating   38 non-null     float64
 5   studio        36 non-null     object
 6   language_id   39 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 2.3+ KB

In [10]:
#Describe will return a answer in aggregate functions
movies.describe()

         movie_id  release_year  imdb_rating  language_id
count   39.000000     39.000000    38.000000    39.000000
mean   120.666667   2006.282051     7.947368     3.435897
std     11.795033     17.945750     1.180869     1.970772
min    101.000000   1946.000000     1.900000     1.000000
25%    110.500000   2000.500000     7.825000     1.000000
50%    121.000000   2013.000000     8.100000     5.000000
75%    130.500000   2018.000000     8.400000     5.000000
max    140.000000   2022.000000     9.300000     7.000000

In [11]:
movies.describe(include="object")

                   title   industry          studio
count                 39         39              36
unique                39          2              22
top     K.G.F: Chapter 2  Hollywood  Marvel Studios
freq                   1         21               8

In [12]:
movies["title"]

0                                K.G.F: Chapter 2
1     Doctor Strange in the Multiverse of Madness
2                           Thor: The Dark World
3                                 Thor: Ragnarok
4                         Thor: Love and Thunder
5                                          Sholay
6                     Dilwale Dulhania Le Jayenge
7                                        3 Idiots
8                        Kabhi Khushi Kabhie Gham
9                                Bajirao Mastani
10                       The Shawshank Redemption
11                                      Inception
12                                   Interstellar
13                       The Pursuit of Happyness
14                                      Gladiator
15                                        Titanic
16                          It's a Wonderful Life
17                                         Avatar
18                                  The Godfather
19                                The Dark Knight
20                               Schindler's List
21                                  Jurassic Park
22                                       Parasite
23                              Avengers: Endgame
24                         Avengers: Infinity War
25                                Pather Panchali
26                               Taare Zameen Par
27                            Munna Bhai M.B.B.S.
28                                             PK
29                                          Sanju
30                      Pushpa: The Rise - Part 1
31                                            RRR
32                       Baahubali: The Beginning
33                              The Kashmir Files
34                              Bajrangi Bhaijaan
35             Captain America: The First Avenger
36            Captain America: The Winter Soldier
37                                         Race 3
38                                      Shershaah
Name: title, dtype: object

In [13]:
movies[["title","release_year","industry"]].head()

                                         title  release_year   industry
0                             K.G.F: Chapter 2          2022  Bollywood
1  Doctor Strange in the Multiverse of Madness          2022  Hollywood
2                        Thor: The Dark World           2013  Hollywood
3                              Thor: Ragnarok           2017  Hollywood
4                      Thor: Love and Thunder           2022  Hollywood

In [14]:
#loc gives according to the index number we have given
movies.loc[0]

movie_id                     101
title           K.G.F: Chapter 2
industry               Bollywood
release_year                2022
imdb_rating                  8.4
studio             Hombale Films
language_id                    3
Name: 0, dtype: object

In [15]:
movies.loc[0:5]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
5,106,Sholay,Bollywood,1975,8.1,United Producers,1

In [16]:
movies.loc[0:5,["title","industry","imdb_rating"]]

                                         title   industry  imdb_rating
0                             K.G.F: Chapter 2  Bollywood          8.4
1  Doctor Strange in the Multiverse of Madness  Hollywood          7.0
2                        Thor: The Dark World   Hollywood          6.8
3                              Thor: Ragnarok   Hollywood          7.9
4                      Thor: Love and Thunder   Hollywood          6.8
5                                       Sholay  Bollywood          8.1

In [17]:
movies.loc[movies["imdb_rating"]>8]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
5,106,Sholay,Bollywood,1975,8.1,United Producers,1
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
25,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7
26,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1
27,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1
28,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [18]:
movies.loc[:,"title"]       #it will print only one column and all the rows

0                                K.G.F: Chapter 2
1     Doctor Strange in the Multiverse of Madness
2                           Thor: The Dark World
3                                 Thor: Ragnarok
4                         Thor: Love and Thunder
5                                          Sholay
6                     Dilwale Dulhania Le Jayenge
7                                        3 Idiots
8                        Kabhi Khushi Kabhie Gham
9                                Bajirao Mastani
10                       The Shawshank Redemption
11                                      Inception
12                                   Interstellar
13                       The Pursuit of Happyness
14                                      Gladiator
15                                        Titanic
16                          It's a Wonderful Life
17                                         Avatar
18                                  The Godfather
19                                The Dark Knight
20                               Schindler's List
21                                  Jurassic Park
22                                       Parasite
23                              Avengers: Endgame
24                         Avengers: Infinity War
25                                Pather Panchali
26                               Taare Zameen Par
27                            Munna Bhai M.B.B.S.
28                                             PK
29                                          Sanju
30                      Pushpa: The Rise - Part 1
31                                            RRR
32                       Baahubali: The Beginning
33                              The Kashmir Files
34                              Bajrangi Bhaijaan
35             Captain America: The First Avenger
36            Captain America: The Winter Soldier
37                                         Race 3
38                                      Shershaah
Name: title, dtype: object

In [19]:
movies.loc[:,"title"].head()

0                               K.G.F: Chapter 2
1    Doctor Strange in the Multiverse of Madness
2                          Thor: The Dark World
3                                Thor: Ragnarok
4                        Thor: Love and Thunder
Name: title, dtype: object

In [20]:
#it will show first row
movies.iloc[0]

movie_id                     101
title           K.G.F: Chapter 2
industry               Bollywood
release_year                2022
imdb_rating                  8.4
studio             Hombale Films
language_id                    3
Name: 0, dtype: object

In [21]:
movies.iloc[0:5]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [22]:
movies.iloc[0:5,0:3]   #0:5 is for row and 0:3 is for column

   movie_id                                        title   industry
0       101                             K.G.F: Chapter 2  Bollywood
1       102  Doctor Strange in the Multiverse of Madness  Hollywood
2       103                        Thor: The Dark World   Hollywood
3       104                              Thor: Ragnarok   Hollywood
4       105                      Thor: Love and Thunder   Hollywood

In [23]:
movies.iloc[:,1]         #it will give first column

0                                K.G.F: Chapter 2
1     Doctor Strange in the Multiverse of Madness
2                           Thor: The Dark World
3                                 Thor: Ragnarok
4                         Thor: Love and Thunder
5                                          Sholay
6                     Dilwale Dulhania Le Jayenge
7                                        3 Idiots
8                        Kabhi Khushi Kabhie Gham
9                                Bajirao Mastani
10                       The Shawshank Redemption
11                                      Inception
12                                   Interstellar
13                       The Pursuit of Happyness
14                                      Gladiator
15                                        Titanic
16                          It's a Wonderful Life
17                                         Avatar
18                                  The Godfather
19                                The Dark Knight
20                               Schindler's List
21                                  Jurassic Park
22                                       Parasite
23                              Avengers: Endgame
24                         Avengers: Infinity War
25                                Pather Panchali
26                               Taare Zameen Par
27                            Munna Bhai M.B.B.S.
28                                             PK
29                                          Sanju
30                      Pushpa: The Rise - Part 1
31                                            RRR
32                       Baahubali: The Beginning
33                              The Kashmir Files
34                              Bajrangi Bhaijaan
35             Captain America: The First Avenger
36            Captain America: The Winter Soldier
37                                         Race 3
38                                      Shershaah
Name: title, dtype: object

In [24]:
movies[movies["industry"] == "Hollywood"]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
13,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
15,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5

In [25]:
movies[movies["release_year"] > 2020]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [26]:
movies[(movies["industry"] == "Hollywood") & (movies["imdb_rating"] > 8)]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5

In [27]:
movies[(movies["industry"] == "Hollywood") | (movies["industry"] == "Bollywood")]  #| this is for "or"

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
5,106,Sholay,Bollywood,1975,8.1,United Producers,1
6,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
8,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
13,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
15,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
25,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7
26,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1
27,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1
28,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1
29,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
32,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [28]:
movies[movies["studio"].isin(["Marvel Studios","Zee Studios"])]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5

In [29]:
movies[movies["release_year"].between(2018,2022)]

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
29,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [30]:
movies.sort_values("imdb_rating").head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5

In [31]:
movies.sort_values("imdb_rating", ascending = False).head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5

In [32]:
movies.sort_values(["title","imdb_rating"], ascending = [True,False]).head(8)        #title will be ascending and rating will be descending

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
32,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5

In [33]:
movies["rating_category"] = movies["imdb_rating"].apply(lambda x: "Excellent" if x > 8 else "Normal")   
#when we want to apply a condition on particular column then we use apply

In [34]:
movies.head(10)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,rating_category
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,Excellent
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,Normal
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,Normal
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal
5,106,Sholay,Bollywood,1975,8.1,United Producers,1,Excellent
6,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1,Normal
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1,Excellent
8,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1,Normal
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1,Normal

In [35]:
movies["movie_age"] = 2026 - movies["release_year"]         #it is to find movie age from current year

In [36]:
movies.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,rating_category,movie_age
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,Excellent,4
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4

In [37]:
movies.rename(columns = {
    "imdb_rating" : "rating",
    "release_year" : "year"                     
},inplace = True)                      #it will only change when inplace = True is written otherwise it will not show changes

In [38]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,Excellent,4
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4

In [39]:
movies.drop(columns = ["language_id"]).head() #drop will delete a column

,movie_id,title,industry,year,rating,studio,rating_category,movie_age
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,Excellent,4
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,Normal,4
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,Normal,13
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,Normal,9
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,Normal,4

In [40]:
movies.drop(index = 0 , inplace = True)         #it will delete a 0 index means 1st row

In [41]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,Sholay,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [42]:
movies.isna().sum()

movie_id           0
title              0
industry           0
year               0
rating             1
studio             3
language_id        0
rating_category    0
movie_age          0
dtype: int64

In [43]:
movies.isnull().sum()

movie_id           0
title              0
industry           0
year               0
rating             1
studio             3
language_id        0
rating_category    0
movie_age          0
dtype: int64

In [44]:
movies["rating"].fillna(movies["rating"].mean(),inplace = True)

C:\Users\jagru\AppData\Local\Temp\ipykernel_20056\1781443015.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies["rating"].fillna(movies["rating"].mean(),inplace = True)

In [45]:
movies["studio"].fillna("unknown",inplace = True)

C:\Users\jagru\AppData\Local\Temp\ipykernel_20056\2211985611.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies["studio"].fillna("unknown",inplace = True)

In [46]:
movies.isnull().sum()

movie_id           0
title              0
industry           0
year               0
rating             0
studio             0
language_id        0
rating_category    0
movie_age          0
dtype: int64

In [47]:
movies.duplicated().sum()

np.int64(0)

In [48]:
movies.drop_duplicates(inplace = True)

In [49]:
movies["title"] = movies["title"].str.upper()

In [50]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,DOCTOR STRANGE IN THE MULTIVERSE OF MADNESS,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,THOR: THE DARK WORLD,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,THOR: RAGNAROK,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,THOR: LOVE AND THUNDER,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,SHOLAY,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [51]:
movies["title"] = movies["title"].str.lower()

In [52]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,sholay,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [53]:
movies["title"].str.len().head()

1    43
2    21
3    15
4    23
5     6
Name: title, dtype: int64

In [54]:
movies[movies["title"].str.contains("Thor",case = False)]        #if case is false then it will ignore input is to lowercase or uppercase 
                                                                 #but if case is true then it will only check exactly written name

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4

In [55]:
movies["title"].str.strip().head()

1    doctor strange in the multiverse of madness
2                           thor: the dark world
3                                 thor: ragnarok
4                         thor: love and thunder
5                                         sholay
Name: title, dtype: object

In [56]:
movies.groupby("industry")["rating"].mean()

industry
Bollywood    7.655008
Hollywood    8.161905
Name: rating, dtype: float64

In [57]:
movies.groupby("industry")["rating"].min()

industry
Bollywood    1.9
Hollywood    6.8
Name: rating, dtype: float64

In [58]:
movies.groupby("industry")["rating"].max()

industry
Bollywood    8.4
Hollywood    9.3
Name: rating, dtype: float64

In [59]:
movies.groupby("industry")["rating"].agg(["max","min","count","mean"])

           max  min  count      mean
industry
Bollywood  8.4  1.9     17  7.655008
Hollywood  9.3  6.8     21  8.161905

In [60]:
movies.groupby("industry").agg({ 
    "rating" : ["max","min","count","mean"],                               #agg is aggregation
    "movie_id" : "count"
})

          rating                      movie_id
             max  min count      mean    count
industry
Bollywood    8.4  1.9    17  7.655008       17
Hollywood    9.3  6.8    21  8.161905       21

In [61]:
movies.groupby("industry").agg({ 
    "rating" : ["max","min","count","mean"],
    "movie_id" : "count",
    "rating_category" : ["max","min"]
})

          rating                      movie_id rating_category
             max  min count      mean    count             max        min
industry
Bollywood    8.4  1.9    17  7.655008       17          Normal  Excellent
Hollywood    9.3  6.8    21  8.161905       21          Normal  Excellent

In [62]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,sholay,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [63]:
financials.head()

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [64]:
financials.shape

(40, 5)

In [65]:
movies.shape

(38, 9)

In [66]:
movie_financials = pd.merge(movies, financials, on = "movie_id",how = "inner" )

In [67]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,sholay,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [68]:
movie_financials.shape

(36, 13)

In [69]:
languages

   language_id      name
0            1     Hindi
1            2    Telugu
2            3   Kannada
3            4     Tamil
4            5   English
5            6    French
6            7   Bengali
7            8  Gujarati

In [70]:
languages.shape

(8, 2)

In [71]:
movies.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,sholay,Bollywood,1975,8.1,United Producers,1,Excellent,51

In [72]:
movie_data = pd.merge(movie_financials,languages, on = "language_id",how = "left")

In [73]:
movie_data.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency,name
0,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4,200.0,954.8,Millions,USD,English
1,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13,165.0,644.8,Millions,USD,English
2,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9,180.0,854.0,Millions,USD,English
3,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4,250.0,670.0,Millions,USD,English
4,107,dilwale dulhania le jayenge,Bollywood,1995,8.0,Yash Raj Films,1,Normal,31,400.0,2000.0,Millions,INR,Hindi

In [74]:
movie_data.columns = movie_data.columns.str.replace("name","language")

In [75]:
movie_data.sample(20)

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency,language
19,124,parasite,Hollywood,2019,8.500000,unknown,5,Excellent,7,15.5,263.1,Millions,USD,English
4,107,dilwale dulhania le jayenge,Bollywood,1995,8.000000,Yash Raj Films,1,Normal,31,400.0,2000.0,Millions,INR,Hindi
24,129,munna bhai m.b.b.s.,Bollywood,2003,8.100000,Vinod Chopra Productions,1,Excellent,23,100.0,410.0,Millions,INR,Hindi
1,103,thor: the dark world,Hollywood,2013,6.800000,Marvel Studios,5,Normal,13,165.0,644.8,Millions,USD,English
26,131,sanju,Bollywood,2018,7.935135,Vinod Chopra Films,1,Normal,8,1.0,5.9,Billions,INR,Hindi
31,136,bajrangi bhaijaan,Bollywood,2015,8.100000,Salman Khan Films,1,Excellent,11,900.0,11690.0,Millions,INR,Hindi
14,119,avatar,Hollywood,2009,7.800000,20th Century Fox,5,Normal,17,237.0,2847.0,Millions,USD,English
9,113,interstellar,Hollywood,2014,8.600000,Warner Bros. Pictures,5,Excellent,12,165.0,701.8,Millions,USD,English
30,135,the kashmir files,Bollywood,2022,8.300000,Zee Studios,1,Excellent,4,250.0,3409.0,Millions,INR,Hindi
33,138,captain america: the winter soldier,Hollywood,2014,7.800000,Marvel Studios,5,Normal,12,177.0,714.4,Millions,USD,English
32,137,captain america: the first avenger,Hollywood,2011,6.900000,Marvel Studios,5,Normal,15,216.7,370.6,Millions,USD,English
35,140,shershaah,Bollywood,2021,8.400000,Dharma Productions,1,Excellent,5,500.0,950.0,Millions,INR,Hindi
25,130,pk,Bollywood,2014,8.100000,Vinod Chopra Films,1,Excellent,12,850.0,8540.0,Millions,INR,Hindi
7,110,bajirao mastani,Bollywood,2015,7.200000,unknown,1,Normal,11,1.4,3.5,Billions,INR,Hindi
8,111,the shawshank redemption,Hollywood,1994,9.300000,Castle Rock Entertainment,5,Excellent,32,25.0,73.3,Millions,USD,English
23,128,taare zameen par,Bollywood,2007,8.300000,unknown,1,Excellent,19,120.0,1350.0,Millions,INR,Hindi
20,125,avengers: endgame,Hollywood,2019,8.400000,Marvel Studios,5,Excellent,7,400.0,2798.0,Millions,USD,English
10,115,the pursuit of happyness,Hollywood,2006,8.000000,Columbia Pictures,5,Normal,20,55.0,307.1,Millions,USD,English
29,134,baahubali: the beginning,Bollywood,2015,8.000000,Arka Media Works,2,Normal,11,1.8,6.5,Billions,INR,Telugu
0,102,doctor strange in the multiverse of madness,Hollywood,2022,7.000000,Marvel Studios,5,Normal,4,200.0,954.8,Millions,USD,English

In [76]:
movie_data["revenue_millions"] = movie_data.apply(
    lambda row: 
    row["revenue"] * 1000
    if row["unit"] == "Billions"
    else row["revenue"],
    axis = 1
)

In [77]:
movie_data["budget_millions"] = movie_data.apply(
    lambda row: 
    row["budget"] * 1000
    if row["unit"] == "Billions"
    else row["budget"],
    axis = 1
)

In [78]:
movie_data["profit_millions"] = movie_data["revenue_millions"] - movie_data["budget_millions"]

In [79]:
movie_data.head()

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency,language,revenue_millions,budget_millions,profit_millions
0,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4,200.0,954.8,Millions,USD,English,954.8,200.0,754.8
1,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13,165.0,644.8,Millions,USD,English,644.8,165.0,479.8
2,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9,180.0,854.0,Millions,USD,English,854.0,180.0,674.0
3,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4,250.0,670.0,Millions,USD,English,670.0,250.0,420.0
4,107,dilwale dulhania le jayenge,Bollywood,1995,8.0,Yash Raj Films,1,Normal,31,400.0,2000.0,Millions,INR,Hindi,2000.0,400.0,1600.0

In [80]:
#Mapping dictionary
industry_map = {
    "Hollywood" : "International",
    "Bollywood" : "Indian"
}

In [81]:
movie_data["Industry_type"] = movie_data["industry"].map(industry_map)

In [82]:
movie_data.sample(5)

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age,budget,revenue,unit,currency,language,revenue_millions,budget_millions,profit_millions,Industry_type
18,123,jurassic park,Hollywood,1993,8.2,Universal Pictures,5,Excellent,33,63.0,1046.0,Millions,USD,English,1046.0,63.0,983.0,International
7,110,bajirao mastani,Bollywood,2015,7.2,unknown,1,Normal,11,1.4,3.5,Billions,INR,Hindi,3500.0,1400.0,2100.0,Indian
4,107,dilwale dulhania le jayenge,Bollywood,1995,8.0,Yash Raj Films,1,Normal,31,400.0,2000.0,Millions,INR,Hindi,2000.0,400.0,1600.0,Indian
25,130,pk,Bollywood,2014,8.1,Vinod Chopra Films,1,Excellent,12,850.0,8540.0,Millions,INR,Hindi,8540.0,850.0,7690.0,Indian
3,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4,250.0,670.0,Millions,USD,English,670.0,250.0,420.0,International

In [83]:
#Pivot table = it will summarize the data in tabular form
pd.pivot_table(movie_data,index = "year",columns = "industry",values = "rating",aggfunc = "mean") #aggfunc is aggregate function

industry  Bollywood  Hollywood
year
1946            NaN       8.60
1955       8.300000        NaN
1972            NaN       9.20
1993            NaN       8.60
1994            NaN       9.30
1995       8.000000        NaN
1997            NaN       7.90
2000            NaN       8.50
2001       7.400000        NaN
2003       8.100000        NaN
2006            NaN       8.00
2007       8.300000        NaN
2008            NaN       9.00
2009       8.400000       7.80
2011            NaN       6.90
2013            NaN       6.80
2014       8.100000       8.20
2015       7.766667        NaN
2017            NaN       7.90
2018       4.917568       8.40
2019            NaN       8.45
2021       8.000000        NaN
2022       8.150000       6.90

In [84]:
pd.pivot_table(movie_data,index = "year", values = "profit_millions",aggfunc = "sum")

      profit_millions
year
1946             0.12
1955         30000.00
1972           283.80
1993          1283.20
1994            48.30
1995          1600.00
1997          2002.00
2000           357.50
2001           970.00
2003           310.00
2006           252.10
2007          1230.00
2008           821.00
2009          6060.00
2011           153.90
2013           479.80
2014          8764.20
2015         17590.00
2017           674.00
2018          7848.00
2019          2645.60
2021          2050.00
2022         10833.80

In [85]:
pd.crosstab(
    movie_data["language"],
    movie_data["industry"]
)

industry  Bollywood  Hollywood
language
Bengali           1          0
English           0         20
Hindi            12          0
Telugu            3          0

In [86]:
pd.crosstab(
    movie_data["industry"],
    movie_data["studio"]
)

studio,20th Century Fox,Arka Media Works,Castle Rock Entertainment,Columbia Pictures,DVV Entertainment,Dharma Productions,Government of West Bengal,Liberty Films,Marvel Studios,Mythri Movie Makers,...,Salman Khan Films,Syncopy,Universal Pictures,Universal Pictures,Vinod Chopra Films,Vinod Chopra Productions,Warner Bros. Pictures,Yash Raj Films,Zee Studios,unknown
industry,,,,,,,,,,,,,,,,,,,,,
Bollywood,0,1,0,0,1,2,1,0,0,1,...,2,0,0,0,3,1,0,1,1,2
Hollywood,1,0,1,1,0,0,0,1,8,0,...,0,1,2,1,0,0,1,0,0,1

In [87]:
#split the movies dataframe into two
df1 = movies.iloc[:10]
df2 = movies.iloc[10:20]

In [88]:
df1.shape

(10, 9)

In [89]:
df2.shape

(10, 9)

In [90]:
df1

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,sholay,Bollywood,1975,8.1,United Producers,1,Excellent,51
6,107,dilwale dulhania le jayenge,Bollywood,1995,8.0,Yash Raj Films,1,Normal,31
7,108,3 idiots,Bollywood,2009,8.4,Vinod Chopra Films,1,Excellent,17
8,109,kabhi khushi kabhie gham,Bollywood,2001,7.4,Dharma Productions,1,Normal,25
9,110,bajirao mastani,Bollywood,2015,7.2,unknown,1,Normal,11
10,111,the shawshank redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5,Excellent,32

In [91]:
df2

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
11,112,inception,Hollywood,2010,8.8,Warner Bros. Pictures,5,Excellent,16
12,113,interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5,Excellent,12
13,115,the pursuit of happyness,Hollywood,2006,8.0,Columbia Pictures,5,Normal,20
14,116,gladiator,Hollywood,2000,8.5,Universal Pictures,5,Excellent,26
15,117,titanic,Hollywood,1997,7.9,Paramount Pictures,5,Normal,29
16,118,it's a wonderful life,Hollywood,1946,8.6,Liberty Films,5,Excellent,80
17,119,avatar,Hollywood,2009,7.8,20th Century Fox,5,Normal,17
18,120,the godfather,Hollywood,1972,9.2,Paramount Pictures,5,Excellent,54
19,121,the dark knight,Hollywood,2008,9.0,Syncopy,5,Excellent,18
20,122,schindler's list,Hollywood,1993,9.0,Universal Pictures,5,Excellent,33

In [92]:
pd.concat([df1,df2])          #concat is concatenation 
#merge will add horizontally
#concat will add vertically and horizontally both

,movie_id,title,industry,year,rating,studio,language_id,rating_category,movie_age
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios,5,Normal,4
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios,5,Normal,13
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios,5,Normal,9
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios,5,Normal,4
5,106,sholay,Bollywood,1975,8.1,United Producers,1,Excellent,51
6,107,dilwale dulhania le jayenge,Bollywood,1995,8.0,Yash Raj Films,1,Normal,31
7,108,3 idiots,Bollywood,2009,8.4,Vinod Chopra Films,1,Excellent,17
8,109,kabhi khushi kabhie gham,Bollywood,2001,7.4,Dharma Productions,1,Normal,25
9,110,bajirao mastani,Bollywood,2015,7.2,unknown,1,Normal,11
10,111,the shawshank redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5,Excellent,32
11,112,inception,Hollywood,2010,8.8,Warner Bros. Pictures,5,Excellent,16
12,113,interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5,Excellent,12
13,115,the pursuit of happyness,Hollywood,2006,8.0,Columbia Pictures,5,Normal,20
14,116,gladiator,Hollywood,2000,8.5,Universal Pictures,5,Excellent,26
15,117,titanic,Hollywood,1997,7.9,Paramount Pictures,5,Normal,29
16,118,it's a wonderful life,Hollywood,1946,8.6,Liberty Films,5,Excellent,80
17,119,avatar,Hollywood,2009,7.8,20th Century Fox,5,Normal,17
18,120,the godfather,Hollywood,1972,9.2,Paramount Pictures,5,Excellent,54
19,121,the dark knight,Hollywood,2008,9.0,Syncopy,5,Excellent,18
20,122,schindler's list,Hollywood,1993,9.0,Universal Pictures,5,Excellent,33

In [93]:
df3 = movies.iloc[:5,0:3]
df4 = movies.iloc[:5,3:6]  #index should be same other wise it will return nan here [:5] is same

In [94]:
df3

   movie_id                                        title   industry
1       102  doctor strange in the multiverse of madness  Hollywood
2       103                        thor: the dark world   Hollywood
3       104                              thor: ragnarok   Hollywood
4       105                      thor: love and thunder   Hollywood
5       106                                       sholay  Bollywood

In [95]:
df4

   year  rating            studio
1  2022     7.0    Marvel Studios
2  2013     6.8    Marvel Studios
3  2017     7.9    Marvel Studios
4  2022     6.8    Marvel Studios
5  1975     8.1  United Producers

In [96]:
pd.concat([df3,df4],axis = 1) #it will add data horizontally using axis = 1 (1 is for row)

,movie_id,title,industry,year,rating,studio
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios
5,106,sholay,Bollywood,1975,8.1,United Producers

In [97]:
#join = join using dataframe index it will add only vertically
df3.join(df4)

,movie_id,title,industry,year,rating,studio
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios
5,106,sholay,Bollywood,1975,8.1,United Producers

In [98]:
df3.join(df4 , how = "right")  #complete right table and only common from left if not common then it will give nan

,movie_id,title,industry,year,rating,studio
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios
5,106,sholay,Bollywood,1975,8.1,United Producers

In [99]:
df3.join(df4, how = "left") #complete left table and only common from right if not common then it will give nan

,movie_id,title,industry,year,rating,studio
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios
5,106,sholay,Bollywood,1975,8.1,United Producers

In [100]:
df3.join(df4, how = "inner")    #it will return only same or matching values   it is basically intersection

,movie_id,title,industry,year,rating,studio
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios
5,106,sholay,Bollywood,1975,8.1,United Producers

In [101]:
df3.join(df4, how = "outer")  #it will return all the values

,movie_id,title,industry,year,rating,studio
1,102,doctor strange in the multiverse of madness,Hollywood,2022,7.0,Marvel Studios
2,103,thor: the dark world,Hollywood,2013,6.8,Marvel Studios
3,104,thor: ragnarok,Hollywood,2017,7.9,Marvel Studios
4,105,thor: love and thunder,Hollywood,2022,6.8,Marvel Studios
5,106,sholay,Bollywood,1975,8.1,United Producers

In [104]:
#Export to Excel = converting all data into Excel
movie_data.to_excel("movie_analysis.xlsx",index = False)